// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Restaurant struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	UpdatedAt string `json:"updated_at"`
}
